// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Rifa_Casa.Data;

#nullable disable

namespace Rifa_Casa.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Rifa_Casa.Models.Buyer", b =>
                {
                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Phone");

                    b.ToTable("Buyers");
                });

            modelBuilder.Entity("Rifa_Casa.Models.Raffle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Available")
                        .HasColumnType("boolean");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<string>("buyerPhone")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("buyerPhone");

                    b.ToTable("Raffles");
                });

            modelBuilder.Entity("Rifa_Casa.Models.Raffle", b =>
                {
                    b.HasOne("Rifa_Casa.Models.Buyer", "buyer")
                        .WithMany("Raffles")
                        .HasForeignKey("buyerPhone");

                    b.Navigation("buyer");
                });

            modelBuilder.Entity("Rifa_Casa.Models.Buyer", b =>
                {
                    b.Navigation("Raffles");
                });
#pragma warning restore 612, 618
        }
    }
}
